---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-meeting-tools-com
  namespace: default
spec:
  secretName: star-meeting-tools-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.meeting-tools.marquescg.com"
  dnsNames:
    - "meeting-tools.marquescg.com"
    - "*.meeting-tools.marquescg.com"
