apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-marquescg-com
  namespace: default
spec:
  secretName: star-marquescg-prod-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.marquescg.com"
  dnsNames:
    - "marquescg.com"
    - "*.marquescg.com"
