apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tylermarques-com
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`tylermarques.com`)
      priority: 10
      services:
        - name: prod-tylermarques-com
          port: 3000
      middlewares:
        - name: redirect-https
