resources:
  - ./../base
  - ./ingress.yaml
namePrefix: prod-
namespace: tylermarques-com
images:
  - name: tylermarques-com
    newName: ghcr.io/tylermarques/tylermarques-com
    newTag: 357287566cf3c4ea7869a5e46d75c7c1ca8f55c5
