resources:
  - ./../base
  - ./ingress.yaml
namePrefix: prod-
namespace: tylermarques-com
images:
  - name: tylermarques-com
    newName: ghcr.io/tylermarques/tylermarques-com
    newTag: b97056438754426563d5437167d9770c08fbc23d
