resources:
  - ./../base
  - ./ingress.yaml
namePrefix: prod-
namespace: meeting-tools-prod

images:
  - name: meeting-tools-backend-dev
    newName: ghcr.io/marquescg/meeting-tools-backend-dev
    newTag: blah
  - name: meeting-tools-frontend-dev
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: blah
  - name: meeting-tools-directory-watcher
    newName: ghcr.io/marquescg/meeting-tools-directory-watcher
    newTag: blah
  - name: meeting-tools-worker
    newName: ghcr.io/marquescg/meeting-tools-worker
    newTag: blah
