resources:
  - ./../base
  - ./ingress.yaml
namePrefix: prod-
namespace: meeting-tools-prod
images:
  - name: meeting-tools-backend-dev
    newName: ghcr.io/tylermarques/meeting-tools-backend-dev
    newTag: blah # actions user should update this... right?
  - name: meeting-tools-frontend-dev
    newName: ghcr.io/tylermarques/meeting-tools-frontend-dev
    newTag: blah # actions user should update this... right?
  - name: meeting-tools-directory_watcher
    newName: ghcr.io/tylermarques/meeting-tools-directory_watcher
    newTag: blah # actions user should update this... right?
  - name: meeting-tools-worker
    newName: ghcr.io/tylermarques/meeting-tools-worker
    newTag: blah # actions user should update this... right?
