namePrefix: prod-
namespace: meeting-tools
resources:
  - ./../base
  - ./ingress.yaml
  - ./config.yaml
images:
  - name: meeting-tools-backend
    newName: ghcr.io/marquescg/meeting-tools-backend
    newTag: 719aff6d25af169e67ff29e8324a50815fcd27ab
  - name: meeting-tools-frontend
    newName: ghcr.io/marquescg/meeting-tools-frontend
    newTag: 719aff6d25af169e67ff29e8324a50815fcd27ab
  - name: meeting-tools-diarization
    newName: ghcr.io/marquescg/meeting-tools-diarization
    newTag: 719aff6d25af169e67ff29e8324a50815fcd27ab
