namePrefix: prod-
namespace: meeting-tools
resources:
  - ./../base
  - ./ingress.yaml
  - ./config.yaml
images:
  - name: meeting-tools-backend
    newName: ghcr.io/marquescg/meeting-tools-backend
    newTag: 1030cb37428b64df7c9c59943338291dae438cb3
  - name: meeting-tools-frontend
    newName: ghcr.io/marquescg/meeting-tools-frontend
    newTag: 1030cb37428b64df7c9c59943338291dae438cb3
  - name: meeting-tools-diarization
    newName: ghcr.io/marquescg/meeting-tools-diarization
    newTag: 1030cb37428b64df7c9c59943338291dae438cb3
