resources:
  - ./../base
  - ./ingress.yaml
namePrefix: prod-
namespace: u-the-bomb-com-prod
images:
  - name: u-the-bomb-com
    newName: ghcr.io/tylermarques/u-the-bomb-com
    newTag: 0b16e9090dcf19129e1535f478fee0baf3c42cc2
