resources:
  - ./../base
  - ./ingress.yaml
namePrefix: prod-
namespace: u-the-bomb-com-prod
images:
  - name: u-the-bomb-com
    newName: ghcr.io/tylermarques/u-the-bomb-com
    newTag: 011e4159d8906a4ca96a1beddffd9676882fe458
