resources:
  - ./../base
  - ./ingress.yaml
namePrefix: dev-
namespace: meeting-tools
images:
  - name: meeting-tools-backend-dev
    newName: ghcr.io/marquescg/meeting-tools-backend-dev
    newTag: 543b110b84968e7b35997db73d00783e9aa3cc12
  - name: meeting-tools-frontend-dev
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: 543b110b84968e7b35997db73d00783e9aa3cc12
  - name: meeting-tools-directory-watcher
    newName: ghcr.io/marquescg/meeting-tools-directory-watcher
    newTag: 543b110b84968e7b35997db73d00783e9aa3cc12
  - name: meeting-tools-worker
    newName: ghcr.io/marquescg/meeting-tools-worker
    newTag: 543b110b84968e7b35997db73d00783e9aa3cc12
