resources:
  - ./../base
  - ./ingress.yaml
namePrefix: dev-
namespace: meeting-tools
images:
  - name: meeting-tools-backend-dev
    newName: ghcr.io/marquescg/meeting-tools-backend-dev
    newTag: 9a512fe0dab8070f7b571b847142eba9556cbc1e
  - name: meeting-tools-frontend-dev
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: 9a512fe0dab8070f7b571b847142eba9556cbc1e
  - name: meeting-tools-directory-watcher
    newName: ghcr.io/marquescg/meeting-tools-directory-watcher
    newTag: 9a512fe0dab8070f7b571b847142eba9556cbc1e
  - name: meeting-tools-worker
    newName: ghcr.io/marquescg/meeting-tools-worker
    newTag: 9a512fe0dab8070f7b571b847142eba9556cbc1e
