namePrefix: dev-
namespace: meeting-tools

resources:
  - ./../base
  - ./ingress.yaml
  - ./config.yaml

patches:
  - path: ./secret-ref.yaml
  - path: ./volumes.yaml
  - path: ./app-name.yaml
  - target:
      group: keda.sh
      version: v1alpha1
      kind: ScaledObject
      name: keda-autoscaler
    path: ./scaler.yaml

images:
  - name: meeting-tools-backend
    newName: ghcr.io/marquescg/meeting-tools-backend
    newTag: 933d9c73b5f6dd4d7f5b65dce3587d2f08760494
  - name: meeting-tools-frontend
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: 933d9c73b5f6dd4d7f5b65dce3587d2f08760494
  - name: meeting-tools-diarization
    newName: ghcr.io/marquescg/meeting-tools-diarization
    newTag: 933d9c73b5f6dd4d7f5b65dce3587d2f08760494

