resources:
  - ./../base
  - ./ingress.yaml
namePrefix: dev-
namespace: meeting-tools-dev
images:
  - name: meeting-tools-backend-dev
    newName: ghcr.io/tylermarques/meeting-tools-backend-dev
    newTag: dev
  - name: meeting-tools-frontend-dev
    newName: ghcr.io/tylermarques/meeting-tools-frontend-dev
    newTag: dev
  - name: meeting-tools-directory_watcher
    newName: ghcr.io/tylermarques/meeting-tools-directory_watcher
    newTag: dev
  - name: meeting-tools-worker
    newName: ghcr.io/tylermarques/meeting-tools-worker
    newTag: dev
