namePrefix: dev-
namespace: meeting-tools
resources:
  - ./../base
  - ./ingress.yaml
  - ./config.yaml
patches:
  - path: ./secret-ref.yaml
  - path: ./volumes.yaml
  - path: ./app-name.yaml
images:
  - name: meeting-tools-backend
    newName: ghcr.io/marquescg/meeting-tools-backend
    newTag: 8ede35a8de03abb697fc7462391c08a51d1d7cad
  - name: meeting-tools-frontend
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: 8ede35a8de03abb697fc7462391c08a51d1d7cad
  - name: meeting-tools-diarization
    newName: ghcr.io/marquescg/meeting-tools-diarization
    newTag: 8ede35a8de03abb697fc7462391c08a51d1d7cad
