namePrefix: dev-
namespace: meeting-tools
resources:
  - ./../base
  - ./ingress.yaml
  - ./config.yaml
patches:
  - path: ./secret-ref.yaml
  - path: ./volumes.yaml
  - path: ./app-name.yaml
images:
  - name: meeting-tools-backend
    newName: ghcr.io/marquescg/meeting-tools-backend
    newTag: 1cd62be1b78b9cda81ef3ab293071c1b954c1233
  - name: meeting-tools-frontend
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: 1cd62be1b78b9cda81ef3ab293071c1b954c1233
  - name: meeting-tools-diarization
    newName: ghcr.io/marquescg/meeting-tools-diarization
    newTag: 1cd62be1b78b9cda81ef3ab293071c1b954c1233
