resources:
  - ./../base
  - ./ingress.yaml
namePrefix: dev-
namespace: meeting-tools
images:
  - name: meeting-tools-backend-dev
    newName: ghcr.io/marquescg/meeting-tools-backend-dev
    newTag: d3cfb47eed7fd91e9e38c244385b5b57b8ae2fd9
  - name: meeting-tools-frontend-dev
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: d3cfb47eed7fd91e9e38c244385b5b57b8ae2fd9
  - name: meeting-tools-directory-watcher
    newName: ghcr.io/marquescg/meeting-tools-directory-watcher
    newTag: d3cfb47eed7fd91e9e38c244385b5b57b8ae2fd9
  - name: meeting-tools-worker
    newName: ghcr.io/marquescg/meeting-tools-worker
    newTag: d3cfb47eed7fd91e9e38c244385b5b57b8ae2fd9
configMapGenerator:
  - name: meeting-tools-config
    literals:
      - backendurl=http://dev-backend-service
      - rabbitmq=amqp://guest:guest@rabbitmq:5672
      - modelfile=/app/whisper-models/ggml-base.en.bin
      - data=/app/data
      - mongodb=mongodb://mongodb:27017/dev-meeting-tools
