resources:
  - ./../base
  - ./ingress.yaml
namePrefix: dev-
namespace: meeting-tools
images:
  - name: meeting-tools-backend-dev
    newName: ghcr.io/marquescg/meeting-tools-backend-dev
    newTag: 865c83c28d2f530bbdc1158eb2bd08fe76d2193b
  - name: meeting-tools-frontend-dev
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: 865c83c28d2f530bbdc1158eb2bd08fe76d2193b
  - name: meeting-tools-directory-watcher
    newName: ghcr.io/marquescg/meeting-tools-directory-watcher
    newTag: 865c83c28d2f530bbdc1158eb2bd08fe76d2193b
  - name: meeting-tools-worker
    newName: ghcr.io/marquescg/meeting-tools-worker
    newTag: 865c83c28d2f530bbdc1158eb2bd08fe76d2193b
configMapGenerator:
  - name: meeting-tools-config
    literals:
      - backendurl=http://dev-backend-service
      - rabbitmq=amqp://guest:guest@rabbitmq:5672
      - modelfile=/app/whisper-models/ggml-base.en.bin
      - data=/app/data
      - mongodb=mongodb://mongodb:27017/dev-meeting-tools
