resources:
  - ./../base
  - ./ingress.yaml
namePrefix: dev-
namespace: meeting-tools
images:
  - name: meeting-tools-backend-dev
    newName: ghcr.io/marquescg/meeting-tools-backend-dev
    newTag: 4b42307ad35d3a6ae0d447ac81b0bd58d240cac4
  - name: meeting-tools-frontend-dev
    newName: ghcr.io/marquescg/meeting-tools-frontend-dev
    newTag: 4b42307ad35d3a6ae0d447ac81b0bd58d240cac4
  - name: meeting-tools-directory-watcher
    newName: ghcr.io/marquescg/meeting-tools-directory-watcher
    newTag: 4b42307ad35d3a6ae0d447ac81b0bd58d240cac4
  - name: meeting-tools-worker
    newName: ghcr.io/marquescg/meeting-tools-worker
    newTag: 4b42307ad35d3a6ae0d447ac81b0bd58d240cac4
configMapGenerator:
  - name: meeting-tools-config
    literals:
      - backendurl=http://dev-backend-service
      - rabbitmq=amqp://guest:guest@rabbitmq:5672
      - model=/app/whisper-models/ggml-base.en.bin
      - data=/app/data
      - mongodb=mongodb://mongodb:27017/dev-meeting-tools
