namePrefix: dev-
namespace: meeting-tools-test

resources:
  - ./../base
  - ./ingress.yaml

patches:
  - path: ./secret-ref.yaml
  - path: ./volumes.yaml

images:
  - name: meeting-tools-backend
    newName: ghcr.io/marquescg/meeting-tools-backend
    newTag: ab65ba1d95644603ce15c5b4ab42ee3eda32test
  - name: meeting-tools-frontend
    newName: ghcr.io/marquescg/meeting-tools-frontend
    newTag: ab65ba1d95644603ce15c5b4ab42ee3eda32test
  - name: meeting-tools-diarization
    newName: ghcr.io/marquescg/meeting-tools-diarization
    newTag: ab65ba1d95644603ce15c5b4ab42ee3eda32tesy

configMapGenerator:
  - name: meeting-tools-config
    literals:
      - backendurl=http://dev.meeting_tools.marquescg.com/api
      - backendurlinternal=http://dev-backend-service.meeting-tools-test.svc.cluster.local:8000
      - rabbitmq=amqp://guest:guest@rabbitmq:5672
      - modelfile=/app/whisper-models/ggml-base.en.bin
      - data=/app/data
      - mongodb=mongodb://mongodb:27017/dev-meeting-tools
