apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: meeting-tools-directory-watcher:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "tasks", "beat", "--loglevel=info"]
        env:
          - name: DATA_DIR
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: data
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: mongo
          - name: HUGGINGFACE_TOKEN
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: huggingface
          - name: FASTAPI_URL
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: fastapi
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        emptyDir: {}
      restartPolicy: Always
