apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: meeting-tools-directory_watcher:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "tasks", "beat", "--loglevel=info"]
        env:
        - # TODO: Ask Tyler how to manage secrets
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        emptyDir: {}
      restartPolicy: Always
