apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-tools-diarization-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting-tools-diarization-worker
  template:
    metadata:
      labels:
        app: meeting-tools-diarization-worker
    spec:
      containers:
      - name: meeting-tools-diarization-worker
        image: meeting-tools-worker:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "tasks", "worker", "--loglevel=info", "--concurrency", "1"]
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: mongo
          - name: DATA_DIR
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: data
          - name: HUGGINGFACE_TOKEN
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: huggingface
          - name: CELERY_BROKER_URL
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: celery
          - name: FASTAPI_URL
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: fastapi
          - name: MODEL_FILE
            valueFrom:
              secretKeyRef:
                name: meeting-tools-secrets
                key: model
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: model-mount
          mountpath: /app/whisper-models
      volumes:
      - name: data-volume
        emptyDir: {}
      restartPolicy: Always
