apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-data-pvc
  namespace: twentycrm
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
