---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photoprism-tylermarques-com
  namespace: photoprism
spec:
  secretName: photoprism-tylermarques-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "photoprism.tylermarques.com"
  dnsNames:
    - "photoprism.tylermarques.com"
